# Numpy

Numpy is the core library for scientific computing in Python. It provides a high performance multidimensional array object, and tools for working with these arrays. It's a sucessor of Numeric package. In 2005, Travis Oliphant created NumPy by incorporating features of the competing Numarray into Numeric, with extensive modifications.I think the concepts and the code examples to a great extend has been explained in the simplest form in his book "Guide to Numpy". Here we'll only be looking at some of the key Numpy concepts that are must or good to know in relevance to machine learning.

We will cover:

* Arrays
* Array indexing
* Datatypes
* Array math
* Broadcasting

Note: For brevity we'll only look at important concepts, if you want to know more you should read the documentation

To use Numpy, we first need to import the `numpy` package:

In [1]:
import numpy as np

### Arrays

A numpy array is a collection of similar data type values, and is indexed by a tuple of nonnegative numbers. The rank of the array is the number of dimensions, and the shape of an array is a tuple of numbers giving the size of the array along each dimension.
We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [2]:
# Create a rank 1 array
a = np.array([0, 1, 2]) 
print type(a)

# this will print the dimension of the array
print a.shape 
print a[0]
print a[1]
print a[2]

# Change an element of the array
a[0] = 5                 
print a                  

<type 'numpy.ndarray'>
(3L,)
0
1
2
[5 1 2]


In [3]:
# Create a rank 2 array
b = np.array([[0,1,2],[3,4,5]])  
print b.shape                     
print b
print b[0, 0], b[0, 1], b[1, 0]   

(2L, 3L)
[[0 1 2]
 [3 4 5]]
0 1 3


In [4]:
print b.shape                   
print b[0, 0], b[0, 1], b[1, 0]

(2L, 3L)
0 1 3


### Creating NumPy array

NumPy also provides many built-in functions to create arrays. Best way to learn this is through examples, so let's jump into the code

In [5]:
# Create a 3x3 array of all zeros
a = np.zeros((3,3)) 
print a

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [6]:
# Create a 2x2 array of all ones
b = np.ones((2,2))  
print b

[[ 1.  1.]
 [ 1.  1.]]


In [7]:
# Create a 3x3 constant array
c = np.full((3,3), 7) 
print c 

[[ 7.  7.  7.]
 [ 7.  7.  7.]
 [ 7.  7.  7.]]


C:\Users\Manoh\Anaconda2\lib\site-packages\numpy\core\numeric.py:301: FutureWarning: in the future, full((3, 3), 7) will return an array of dtype('int32')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


In [8]:
# Create a 3x3 array filled with random values
d = np.random.random((3,3)) 
print d

[[ 0.46946625  0.57257208  0.73061006]
 [ 0.55029247  0.10777979  0.3525923 ]
 [ 0.85454215  0.8169908   0.63477789]]


In [9]:
# Create a 3x3 identity matrix
e = np.eye(3)        
print e

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [10]:
# convert list to array
f = np.array([2, 3, 1, 0]) 
print f

[2 3 1 0]


In [11]:
# arange() will create arrays with regularly incrementing values
g = np.arange(20)
print g

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [12]:
# note mix of tuple and lists 
h = np.array([[0, 1,2.0],[0,0,0],(1+1j,3.,2.)])                           
print h

[[ 0.+0.j  1.+0.j  2.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j]
 [ 1.+1.j  3.+0.j  2.+0.j]]


In [13]:
# create an array of range with float data type 
i = np.arange(1, 8, dtype=np.float)
print i

[ 1.  2.  3.  4.  5.  6.  7.]


In [14]:
# linspace() will create arrays with a specified number of items which are 
# spaced equally between the specified beginning and end values
j = np.linspace(2., 4., 5)
print j

[ 2.   2.5  3.   3.5  4. ]


In [15]:
# indices() will create a set of arrays stacked as a one-higher 
# dimensioned array, one per dimension with each representing variation 
# in that dimension
k = np.indices((2,2))
print k

[[[0 0]
  [1 1]]

 [[0 1]
  [0 1]]]


### Datatypes

Array is a collection of items of same data type, NumPy supports and provided built-in funtion to construct array with optional argument to explicitly specify required datatype. 

In [16]:
# Let numpy choose the datatype
x = np.array([0, 1])  
y = np.array([2.0, 3.0])  

# Force a particular datatype
z = np.array([5, 6], dtype=np.int64)  

print x.dtype, y.dtype, z.dtype

int32 float64 int64


You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

## Array Indexing

Numpy offers several ways to index into arrays. Standard Python x[obj] syntax can be used to index NumPyarray, where x is the array and obj the selection.

There are three kinds of indexing available
•	Field access
•	Basic slicing
•	Advanced indexing

### Field Access

If the ndarray object is a structured array the fields of the array can be accessed by indexing the array with strings, dictionary like. Indexing x['field-name'] returns a new view to the array, which is of the same shape as x, except when the field is a sub-array, but of data type x.dtype['field-name'] and contains only the part of the data in the specified field.

In [17]:
x = np.zeros((3,3), dtype=[('a', np.int32), ('b', np.float64, (3,3))])
print "x['a'].shape: ",x['a'].shape
print "x['a'].dtype: ", x['a'].dtype

print "x['b'].shape: ", x['b'].shape
print "x['b'].dtype: ", x['b'].dtype

x['a'].shape:  (3L, 3L)
x['a'].dtype:  int32
x['b'].shape:  (3L, 3L, 3L, 3L)
x['b'].dtype:  float64


### Basic Slicing

NumPy arrays can be sliced, similar to lists. You must specify a slice for each dimension of the array as the arrays may be multidimensional.
The basic slice syntax is i:j:k where i is the starting index, j is the stopping index, and k is the step and k not equal to 0. This selects the m elements in the corresponding dimension, with index values i, i + k, ...,i + (m - 1) k where m = q + (r not equal to 0) and q and r are the quotient and remainder obtained by dividing j - i by k: j - i = q k + r, so that i + (m - 1) k < j.

In [18]:
x = np.array([5, 6, 7, 8, 9])
x[1:7:2]

array([6, 8])

Negative k makes stepping go towards smaller indices. Negative i and j are interpreted as n + i and n + j where n is the number of elements in the corresponding dimension.

In [19]:
print x[-2:5]
print x[-1:1:-1]

[8 9]
[9 8 7]


If n is the number of items in the dimension being sliced. Then if i is not given then it defaults to 0 for k > 0 and n - 1 for k < 0 . If j is not given it defaults to n for k > 0 and -1 for k < 0 . If k is not given it defaults to 1. Note that :: is the same as : and means select all indices along this axis.

In [20]:
x[4:]

array([9])

If the number of objects in the selection tuple is less than N , then : is assumed for any subsequent dimensions.

In [21]:
y = np.array([[[0],[1],[2],[3]], [[4],[5],[6]],[7]])
print "Shape of y: ", y.shape
y[1:3]

Shape of y:  (3L,)


array([[[4], [5], [6]], [7]], dtype=object)

Ellipsis expand to the number of : objects needed to make a selection tuple of the same length as x.ndim. There may only be a single ellipsis present.

In [22]:
x[...,0]

array(5)

In [23]:
# Create a rank 2 array with shape (3, 4)
a = np.array([[5,6,7,8], [1,2,3,4], [9,10,11,12]])
print "Array a: ", a

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print "Array b: ", b

Array a:  [[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]
Array b:  [[6 7]
 [2 3]]


A slice of an array is just a view into the same data, so any modification will modify the original array.

In [24]:
print a[0, 1]  
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print a[0, 1] 

6
77


Middle row array can be accessed in two ways. 1) Slices along with integer indexing will result in an arry of lower rank. 2) Using only slices will result in same rank array. 

In [25]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print a

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Two ways of accessing the data in the middle row of the array.
Mixing integer indexing with slices yields an array of lower rank,
while using only slices yields an array of the same rank as the
original array:

In [26]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print row_r1, row_r1.shape 
print row_r2, row_r2.shape
print row_r3, row_r3.shape

[5 6 7 8] (4L,)
[[5 6 7 8]] (1L, 4L)
[[5 6 7 8]] (1L, 4L)


In [27]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print col_r1, col_r1.shape
print col_r2, col_r2.shape

[ 2  6 10] (3L,)
[[ 2]
 [ 6]
 [10]] (3L, 1L)


### Advanced Indexing
Integer array indexing: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, iInteger array indexing allows you to construct arbitrary random arrays using the data from another array. 

In [28]:
a = np.array([[1,2], [3, 4]])

# An example of integer array indexing.
# The returned array will have shape (2,) and 
print a[[0, 1], [0, 1]]

# The above example of integer array indexing is equivalent to this:
print np.array([a[0, 0], a[1, 1]])

[1 4]
[1 4]


In [29]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print a[[0, 0], [1, 1]]

# Equivalent to the previous integer array indexing example
print np.array([a[0, 1], a[0, 1]])

[2 2]
[2 2]


Boolean array indexing: This is useful to pick a random element from array, which is often used for filtering elements that satisfy a given condition.

In [30]:
a = np.array([[1,2], [3, 4], [5, 6]])
# Find the elements of a that are bigger than 2
print (a > 2)  

# to get the actual value
print a[a > 2]

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


### Array math

Basic mathematical functions are available as operator and also as functions in NumPy. It operates elementwise on array. 

In [31]:
x = np.array([[1,2],[3,4],[5,6]])
y = np.array([[7,8],[9,10],[11,12]])

# Elementwise sum; both produce the array
print x + y
print np.add(x, y)

[[ 8 10]
 [12 14]
 [16 18]]
[[ 8 10]
 [12 14]
 [16 18]]


In [32]:
# Elementwise difference; both produce the array
print x - y
print np.subtract(x, y)

[[-6 -6]
 [-6 -6]
 [-6 -6]]
[[-6 -6]
 [-6 -6]
 [-6 -6]]


In [33]:
# Elementwise product; both produce the array
print x * y
print np.multiply(x, y)

[[ 7 16]
 [27 40]
 [55 72]]
[[ 7 16]
 [27 40]
 [55 72]]


In [34]:
# Elementwise division; both produce the array
print x / y
print np.divide(x, y)

[[0 0]
 [0 0]
 [0 0]]
[[0 0]
 [0 0]
 [0 0]]


In [35]:
# Elementwise square root; produces the array
print np.sqrt(x)

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]
 [ 2.23606798  2.44948974]]


We can use "dot" function to calculate inner products of vectors or to multiply matrices or multiply vector by matrix

In [36]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

a = np.array([9,10])
b = np.array([11, 12])

# Inner product of vectors; both produce 219
print a.dot(b)
print np.dot(a, b)

219
219


In [37]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print x.dot(a)
print np.dot(x, a)

[29 67]
[29 67]


In [38]:
# Matrix / matrix product; both produce the rank 2 array
print x.dot(y)
print np.dot(x, y)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays, one of the most useful is `sum`:

In [39]:
x = np.array([[1,2],[3,4]])

# Compute sum of all elements
print np.sum(x)  
# Compute sum of each column
print np.sum(x, axis=0)  
# Compute sum of each row
print np.sum(x, axis=1)  

10
[4 6]
[3 7]


Transpose is one of the common operation often performed on matrix, which can be achieved using T attribute of an array object.

In [40]:
print x
print x.T

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [41]:
v = np.array([1,2,3])
print v 
print v.T

[1 2 3]
[1 2 3]


### Broadcasting

Broadcasting enables arithmetic operations to be performed between different shaped arrays. Let's look at a simple example of adding a constant vector to each row of matrix. 

In [42]:
# create a matrix
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
# create a vector
v = np.array([1, 0, 1])

# Create an empty matrix with the same shape as a
b = np.empty_like(a)   

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(3):
    b[i, :] = a[i, :] + v

print b

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


If you have to perform the above operation on a large matrix through loop in Python could be slow. Let's look at an alternative approach.

In [43]:
# Stack 3 copies of v on top of each other
vv = np.tile(v, (3, 1))  
print vv 

[[1 0 1]
 [1 0 1]
 [1 0 1]]


In [44]:
# Add x and vv elementwise
b = a + vv  
print b

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v

In [45]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
v = np.array([1, 0, 1])

# Add v to each row of a using broadcasting
b = a + v  
print b

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


Let's look at some applications of broadcasting:

In [46]:
# Compute outer product of vectors
# v has shape (3,)
v = np.array([1,2,3])
# w has shape (2,)
w = np.array([4,5]) 
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print np.reshape(v, (3, 1)) * w

[[ 4  5]
 [ 8 10]
 [12 15]]


In [47]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3)

print x + v

[[2 4 6]
 [5 7 9]]


In [48]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column

print (x.T + w).T

[[ 5  6  7]
 [ 9 10 11]]


In [49]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print x + np.reshape(w, (2, 1))

[[ 5  6  7]
 [ 9 10 11]]


In [50]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print x * 2

[[ 2  4  6]
 [ 8 10 12]]


Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.